package com.aravind.spectra.ui

import androidx.compose.ui.graphics.Color

// Same stops as the web version's worker.js, so a spectrogram looks
// identical whether it was generated by the app or the browser tool.
private val STOPS = listOf(
    0.00f to Triple(8, 8, 22),
    0.16f to Triple(32, 20, 95),
    0.36f to Triple(115, 25, 135),
    0.56f to Triple(205, 35, 70),
    0.74f to Triple(238, 105, 20),
    0.88f to Triple(251, 193, 45),
    1.00f to Triple(255, 251, 232)
)

fun dbToColor(db: Float, minDb: Float, maxDb: Float): Color {
    var t = (db - minDb) / (maxDb - minDb)
    if (t < 0f) t = 0f
    if (t > 1f) t = 1f
    for (i in 0 until STOPS.size - 1) {
        val (t0, c0) = STOPS[i]
        val (t1, c1) = STOPS[i + 1]
        if (t in t0..t1) {
            val f = if (t1 > t0) (t - t0) / (t1 - t0) else 0f
            val r = (c0.first + (c1.first - c0.first) * f) / 255f
            val g = (c0.second + (c1.second - c0.second) * f) / 255f
            val b = (c0.third + (c1.third - c0.third) * f) / 255f
            return Color(r, g, b)
        }
    }
    val (_, last) = STOPS.last()
    return Color(last.first / 255f, last.second / 255f, last.third / 255f)
}
